#!/usr/bin/env python3
"""
Run this script once after downloading your CSVs:
    python3 convert_data.py

It reads PokemonBaseStat&Types.csv (or pokemon.csv) and dps.csv
from the same folder
and writes data.js which embeds them as JS variables.
Place data.js in the same folder as index.html.
"""
import os, sys

def csv_to_js_string(filepath):
    if not os.path.exists(filepath):
        print(f"  ⚠️  {filepath} not found — skipping")
        return None
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    # Escape backticks and backslashes for JS template literal
    content = content.replace('\\', '\\\\').replace('`', '\\`').replace('${', '\\${')
    return content

def first_existing(paths):
    for p in paths:
        if os.path.exists(p):
            return p
    return None

print("Converting CSVs to data.js...")

# Prefer the local base-stats file the site user provided.
pokemon_source = first_existing(['PokemonBaseStat&Types.csv', 'pokemon.csv'])
dps_source = first_existing(['DPS.csv', 'dps.csv'])

pokemon_csv = csv_to_js_string(pokemon_source) if pokemon_source else None
dps_csv     = csv_to_js_string(dps_source) if dps_source else None

if not pokemon_csv and not dps_csv:
    print("\n❌ No CSV files found.")
    print("   Expected one of: PokemonBaseStat&Types.csv, pokemon.csv, dps.csv")
    sys.exit(1)

lines = ["// AUTO-GENERATED by convert-data.py — do not edit manually",
         "// Re-run convert-data.py after updating your Google Sheets\n"]

if pokemon_csv:
    lines.append(f"window.POKEMON_CSV_DATA = `{pokemon_csv}`;")
    rows = pokemon_csv.strip().count('\n')
    print(f"  ✅ {pokemon_source} → {rows} rows embedded")
else:
    lines.append("window.POKEMON_CSV_DATA = null;")

lines.append("")

if dps_csv:
    lines.append(f"window.DPS_CSV_DATA = `{dps_csv}`;")
    rows = dps_csv.strip().count('\n')
    print(f"  ✅ {dps_source} → {rows} rows embedded")
else:
    lines.append("window.DPS_CSV_DATA = null;")

with open('data.js', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print("\n✅ data.js written successfully!")
print("   Add this line to index.html BEFORE script.js:")
print('   <script src="data.js"></script>')